// node_modules/onejs-core/dist/dom/dom-style.js
var DomStyleWrapper = class {
  _domStyle;
  // Making this public so that Proxy's setProperty can access it
  constructor(domStyle) {
    this._domStyle = domStyle;
    return new Proxy(this, {
      set(target, prop, value, receiver) {
        if (typeof prop === "string" && !(prop in target)) {
          target.setProperty(prop, value);
          return true;
        }
        return Reflect.set(target, prop, value, receiver);
      },
      get(target, prop, receiver) {
        if (typeof prop === "string" && !(prop in target)) {
          return target.getProperty(prop);
        }
        return Reflect.get(target, prop, receiver);
      }
    });
  }
  getProperty(name) {
    return this._domStyle.getProperty(name);
  }
  setProperty(name, value) {
    this._domStyle.setProperty(name, value);
  }
};

// node_modules/onejs-core/dist/dom/dom.js
var DomWrapper = class _DomWrapper {
  get _dom() {
    return this.dom;
  }
  get ve() {
    return this.dom.ve;
  }
  get childNodes() {
    if (this.cachedChildNodes)
      return this.cachedChildNodes;
    this.cachedChildNodes = new Array(this.dom.childNodes.Length);
    var i = this.dom.childNodes.Length;
    while (i--) {
      this.cachedChildNodes[i] = new _DomWrapper(this.dom.childNodes.get_Item(i));
    }
    return this.cachedChildNodes;
  }
  get firstChild() {
    return this.dom.firstChild ? new _DomWrapper(this.dom.firstChild) : null;
  }
  get parentNode() {
    return this.dom.parentNode ? new _DomWrapper(this.dom.parentNode) : null;
  }
  get nextSibling() {
    return this.dom.nextSibling ? new _DomWrapper(this.dom.nextSibling) : null;
  }
  get nodeType() {
    return this.dom.nodeType;
  }
  get style() {
    return this.domStyleWrapper;
  }
  get Id() {
    return this.dom.Id;
  }
  set Id(value) {
    this.dom.Id = value;
  }
  get key() {
    return this.dom.key;
  }
  set key(value) {
    this.dom.key = value;
  }
  get value() {
    return this.dom.value;
  }
  get checked() {
    return this.dom.checked;
  }
  get data() {
    return this.dom.data;
  }
  set data(value) {
    this.dom.data = value;
  }
  get className() {
    return this.dom.className;
  }
  set className(value) {
    this.dom.className = value;
  }
  get classList() {
    return this.domTokenList;
  }
  /**
   * Not using private fields because of issues with the `#private;` line
   * generated by tsc
   */
  dom;
  domStyleWrapper;
  domTokenList;
  cachedChildNodes = null;
  boundListeners = /* @__PURE__ */ new WeakMap();
  constructor(dom) {
    this.dom = dom;
    this.domStyleWrapper = new DomStyleWrapper(dom.style);
    this.domTokenList = new DomTokenList(dom);
  }
  appendChild(child) {
    if (!child)
      return;
    this.dom.appendChild(child.dom);
    this.cachedChildNodes = null;
  }
  removeChild(child) {
    if (!child)
      return;
    this.dom.removeChild(child.dom);
    this.cachedChildNodes = null;
  }
  insertBefore(a, b) {
    this.dom.insertBefore(a?._dom, b?._dom);
    this.cachedChildNodes = null;
  }
  insertAfter(a, b) {
    this.dom.insertAfter(a?._dom, b?._dom);
    this.cachedChildNodes = null;
  }
  contains(child) {
    if (!child)
      return false;
    return this.dom.contains(child._dom);
  }
  clearChildren() {
    this.dom.clearChildren();
    this.cachedChildNodes = null;
  }
  focus() {
    this.dom.focus();
  }
  addEventListener(type, listener, options3) {
    let boundListener = this.boundListeners.get(listener);
    if (!boundListener) {
      boundListener = listener.bind(this);
      this.boundListeners.set(listener, boundListener);
    }
    if (typeof options3 === "object" && options3.once) {
      const onceWrapper = (event) => {
        boundListener(event);
        this.dom.removeEventListener(type, onceWrapper, false);
      };
      this.dom.addEventListener(type, onceWrapper, false);
    } else {
      this.dom.addEventListener(type, boundListener, options3 ? true : false);
    }
  }
  removeEventListener(type, listener, useCapture) {
    const boundListener = this.boundListeners.get(listener);
    if (boundListener) {
      this.dom.removeEventListener(type, boundListener, useCapture ? true : false);
      this.boundListeners.delete(listener);
    }
  }
  setAttribute(name, value) {
    this.dom.setAttribute(name, value);
  }
  removeAttribute(name) {
    this.dom.removeAttribute(name);
  }
  /**
   * Returns all elements matching the specified selector.
   * Supports basic selectors:
   * - Tag names: 'div'
   * - IDs: '#myId'
   * - Classes: '.myClass'
   * - Combinations: 'div.myClass#myId'
   */
  querySelectorAll(selector) {
    const selectorInfo = parseSelector(selector);
    const results = [];
    function traverse(element) {
      if (elementMatchesSelector(element, selectorInfo)) {
        results.push(element);
      }
      for (const child of element.childNodes) {
        traverse(child);
      }
    }
    traverse(this);
    return results;
  }
  /**
   * Returns the first element matching the specified selector.
   * Supports the same basic selectors as querySelectorAll.
   */
  querySelector(selector) {
    const selectorInfo = parseSelector(selector);
    function traverse(element) {
      if (elementMatchesSelector(element, selectorInfo)) {
        return element;
      }
      for (const child of element.childNodes) {
        const match = traverse(child);
        if (match) {
          return match;
        }
      }
      return null;
    }
    return traverse(this);
  }
};
function parseSelector(selector) {
  const selectorInfo = {
    classes: []
  };
  const idMatch = selector.match(/#([^.#\s]+)/);
  if (idMatch) {
    selectorInfo.id = idMatch[1];
    selector = selector.replace(idMatch[0], "");
  }
  const classMatches = selector.match(/\.([^.#\s]+)/g);
  if (classMatches) {
    selectorInfo.classes = classMatches.map((c) => c.substring(1));
    selector = selector.replace(/\.[^.#\s]+/g, "");
  }
  const tagName = selector.trim();
  if (tagName) {
    selectorInfo.tag = tagName.toLowerCase();
  }
  return selectorInfo;
}
function elementMatchesSelector(element, selectorInfo) {
  if (selectorInfo.tag && element.ve.GetType().Name.toLowerCase() !== selectorInfo.tag) {
    return false;
  }
  if (selectorInfo.id && element.Id !== selectorInfo.id) {
    return false;
  }
  if (selectorInfo.classes.length > 0) {
    const elementClasses = element.className.split(" ").filter((c) => c);
    for (const className of selectorInfo.classes) {
      if (!elementClasses.includes(className)) {
        return false;
      }
    }
  }
  return true;
}
var DomTokenList = class {
  dom;
  constructor(dom) {
    this.dom = dom;
  }
  _tokens() {
    return this.dom.className.trim().split(/\s+/).filter(Boolean);
  }
  _update(tokens) {
    this.dom.className = tokens.join(" ");
  }
  add(...tokens) {
    const set = new Set(this._tokens());
    tokens.forEach((t) => t && set.add(t));
    this._update(Array.from(set));
  }
  remove(...tokens) {
    const set = new Set(this._tokens());
    tokens.forEach((t) => set.delete(t));
    this._update(Array.from(set));
  }
  toggle(token, force) {
    if (!token)
      return false;
    const has = this.contains(token);
    if (force === true || !has && force !== false) {
      this.add(token);
      return true;
    }
    if (has && (force === false || force === void 0)) {
      this.remove(token);
      return false;
    }
    return has;
  }
  contains(token) {
    return this._tokens().includes(token);
  }
  replace(oldToken, newToken) {
    if (!this.contains(oldToken))
      return false;
    const tokens = this._tokens().map((t) => t === oldToken ? newToken : t);
    this._update(tokens);
    return true;
  }
  toString() {
    return this.dom.className;
  }
  get length() {
    return this._tokens().length;
  }
  item(index) {
    const t = this._tokens();
    return index >= 0 && index < t.length ? t[index] : null;
  }
  [Symbol.iterator]() {
    return this._tokens()[Symbol.iterator]();
  }
};

// node_modules/onejs-core/dist/dom/document.js
var { Vector2 } = CS.UnityEngine;
var DocumentWrapper = class {
  get _doc() {
    return this.#doc;
  }
  #doc;
  #body;
  /**
   * The body/root element of the document. Will be null for Editor documents.
   */
  get body() {
    return this.#body;
  }
  constructor(doc) {
    this.#doc = doc;
    this.#body = doc.body ? new DomWrapper(doc.body) : null;
  }
  addRuntimeUSS(uss) {
    this.#doc.addRuntimeUSS(uss);
  }
  clearRuntimeStyleSheets() {
    this.#doc.clearRuntimeStyleSheets();
  }
  createElement(tagName, options3) {
    return new DomWrapper(this.#doc.createElement(tagName));
  }
  createElementNS(ns, tagName, options3) {
    tagName = typeof tagName === "string" ? tagName : "div";
    return new DomWrapper(this.#doc.createElement(tagName));
  }
  createTextNode(text) {
    return new DomWrapper(this.#doc.createTextNode(text));
  }
  getElementById(id) {
    return new DomWrapper(this.#doc.getElementById(id));
  }
  querySelectorAll(selector) {
    let doms = this.#doc.querySelectorAll(selector);
    let res = [];
    for (let i = 0; i < doms.Length; i++) {
      res.push(new DomWrapper(doms.get_Item(i)));
    }
    return res;
  }
  elementFromPoint(x, y) {
    const root = this.body;
    if (!root)
      return null;
    const hitTest = (node) => {
      if (!node.ve.worldBound.Contains(new Vector2(x, y)))
        return null;
      for (let i = node.childNodes.length - 1; i >= 0; i--) {
        const hit = hitTest(node.childNodes[i]);
        if (hit)
          return hit;
      }
      return node;
    };
    return hitTest(root);
  }
  elementsFromPoint(x, y) {
    const root = this.body;
    if (!root)
      return [];
    const hits = [];
    const collect = (node) => {
      if (!node.ve.worldBound.Contains(new Vector2(x, y)))
        return;
      for (let i = node.childNodes.length - 1; i >= 0; i--) {
        collect(node.childNodes[i]);
      }
      hits.push(node);
    };
    collect(root);
    return hits;
  }
};

// node_modules/css-simple-parser/dist/constants.js
var TOKEN_TYPE = {
  SELECTOR: 1,
  BODY_START: 2,
  BODY_END: 3
};

// node_modules/css-simple-parser/dist/tokenizer.js
var { SELECTOR, BODY_START, BODY_END } = TOKEN_TYPE;

// node_modules/css-simple-parser/dist/parse.js
var { SELECTOR: SELECTOR2, BODY_START: BODY_START2, BODY_END: BODY_END2 } = TOKEN_TYPE;

// node_modules/onejs-core/dist/index.js
if (typeof globalThis.___document != "undefined") {
  globalThis.onejsDocument = new DocumentWrapper(globalThis.___document);
  if (!globalThis.ONEJS_WEBGL) {
    globalThis.document = globalThis.onejsDocument;
  }
}

// node_modules/onejs-preact/constants.js
var MODE_HYDRATE = 1 << 5;
var MODE_SUSPENDED = 1 << 7;
var INSERT_VNODE = 1 << 16;
var MATCHED = 1 << 17;
var RESET_MODE = ~(MODE_HYDRATE | MODE_SUSPENDED);
var EMPTY_OBJ = (
  /** @type {any} */
  {}
);
var EMPTY_ARR = [];
var IS_NON_DIMENSIONAL = /acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord|itera/i;

// node_modules/onejs-preact/util.js
var isArray = Array.isArray;
function assign(obj, props) {
  for (let i in props)
    obj[i] = props[i];
  return (
    /** @type {O & P} */
    obj
  );
}
function removeNode(node) {
  let parentNode = node.parentNode;
  if (parentNode)
    parentNode.removeChild(node);
}
var slice = EMPTY_ARR.slice;

// node_modules/onejs-preact/diff/catch-error.js
function _catchError(error, vnode, oldVNode, errorInfo) {
  let component, ctor, handled;
  for (; vnode = vnode._parent; ) {
    if ((component = vnode._component) && !component._processingException) {
      try {
        ctor = component.constructor;
        if (ctor && ctor.getDerivedStateFromError != null) {
          component.setState(ctor.getDerivedStateFromError(error));
          handled = component._dirty;
        }
        if (component.componentDidCatch != null) {
          component.componentDidCatch(error, errorInfo || {});
          handled = component._dirty;
        }
        if (handled) {
          return component._pendingError = component;
        }
      } catch (e) {
        error = e;
      }
    }
  }
  throw error;
}

// node_modules/onejs-preact/options.js
var options = {
  _catchError
};
var options_default = options;

// node_modules/onejs-preact/create-element.js
var vnodeId = 0;
function createElement(type, props, children) {
  let normalizedProps = {}, key, ref, i;
  for (i in props) {
    if (i == "key")
      key = props[i];
    else if (i == "ref")
      ref = props[i];
    else
      normalizedProps[i] = props[i];
  }
  if (arguments.length > 2) {
    normalizedProps.children = arguments.length > 3 ? slice.call(arguments, 2) : children;
  }
  if (typeof type == "function" && type.defaultProps != null) {
    for (i in type.defaultProps) {
      if (normalizedProps[i] === void 0) {
        normalizedProps[i] = type.defaultProps[i];
      }
    }
  }
  return createVNode(type, normalizedProps, key, ref, null);
}
function createVNode(type, props, key, ref, original) {
  const vnode = {
    type,
    props,
    key,
    ref,
    _children: null,
    _parent: null,
    _depth: 0,
    _dom: null,
    // _nextDom must be initialized to undefined b/c it will eventually
    // be set to dom.nextSibling which can return `null` and it is important
    // to be able to distinguish between an uninitialized _nextDom and
    // a _nextDom that has been set to `null`
    _nextDom: void 0,
    _component: null,
    constructor: void 0,
    _original: original == null ? ++vnodeId : original,
    _index: -1,
    _flags: 0
  };
  if (original == null && options_default.vnode != null)
    options_default.vnode(vnode);
  return vnode;
}
function Fragment(props) {
  return props.children;
}

// node_modules/onejs-preact/component.js
function BaseComponent(props, context) {
  this.props = props;
  this.context = context;
}
BaseComponent.prototype.setState = function(update, callback) {
  let s;
  if (this._nextState != null && this._nextState !== this.state) {
    s = this._nextState;
  } else {
    s = this._nextState = assign({}, this.state);
  }
  if (typeof update == "function") {
    update = update(assign({}, s), this.props);
  }
  if (update) {
    assign(s, update);
  }
  if (update == null)
    return;
  if (this._vnode) {
    if (callback) {
      this._stateCallbacks.push(callback);
    }
    enqueueRender(this);
  }
};
BaseComponent.prototype.forceUpdate = function(callback) {
  if (this._vnode) {
    this._force = true;
    if (callback)
      this._renderCallbacks.push(callback);
    enqueueRender(this);
  }
};
BaseComponent.prototype.render = Fragment;
function getDomSibling(vnode, childIndex) {
  if (childIndex == null) {
    return vnode._parent ? getDomSibling(vnode._parent, vnode._index + 1) : null;
  }
  let sibling;
  for (; childIndex < vnode._children.length; childIndex++) {
    sibling = vnode._children[childIndex];
    if (sibling != null && sibling._dom != null) {
      return sibling._dom;
    }
  }
  return typeof vnode.type == "function" ? getDomSibling(vnode) : null;
}
function renderComponent(component) {
  let oldVNode = component._vnode, oldDom = oldVNode._dom, commitQueue = [], refQueue = [];
  if (component._parentDom) {
    const newVNode = assign({}, oldVNode);
    newVNode._original = oldVNode._original + 1;
    if (options_default.vnode)
      options_default.vnode(newVNode);
    diff(
      component._parentDom,
      newVNode,
      oldVNode,
      component._globalContext,
      component._parentDom.namespaceURI,
      oldVNode._flags & MODE_HYDRATE ? [oldDom] : null,
      commitQueue,
      oldDom == null ? getDomSibling(oldVNode) : oldDom,
      !!(oldVNode._flags & MODE_HYDRATE),
      refQueue
    );
    newVNode._original = oldVNode._original;
    newVNode._parent._children[newVNode._index] = newVNode;
    commitRoot(commitQueue, newVNode, refQueue);
    if (newVNode._dom != oldDom) {
      updateParentDomPointers(newVNode);
    }
  }
}
function updateParentDomPointers(vnode) {
  if ((vnode = vnode._parent) != null && vnode._component != null) {
    vnode._dom = vnode._component.base = null;
    for (let i = 0; i < vnode._children.length; i++) {
      let child = vnode._children[i];
      if (child != null && child._dom != null) {
        vnode._dom = vnode._component.base = child._dom;
        break;
      }
    }
    return updateParentDomPointers(vnode);
  }
}
var rerenderQueue = [];
var prevDebounce;
var defer = typeof Promise == "function" ? Promise.prototype.then.bind(Promise.resolve()) : setTimeout;
function enqueueRender(c) {
  if (!c._dirty && (c._dirty = true) && rerenderQueue.push(c) && !process._rerenderCount++ || prevDebounce !== options_default.debounceRendering) {
    prevDebounce = options_default.debounceRendering;
    (prevDebounce || defer)(process);
  }
}
var depthSort = (a, b) => a._vnode._depth - b._vnode._depth;
function process() {
  let c;
  rerenderQueue.sort(depthSort);
  while (c = rerenderQueue.shift()) {
    if (c._dirty) {
      let renderQueueLength = rerenderQueue.length;
      renderComponent(c);
      if (rerenderQueue.length > renderQueueLength) {
        rerenderQueue.sort(depthSort);
      }
    }
  }
  process._rerenderCount = 0;
}
process._rerenderCount = 0;

// node_modules/onejs-preact/diff/children.js
function diffChildren(parentDom, renderResult, newParentVNode, oldParentVNode, globalContext, namespace, excessDomChildren, commitQueue, oldDom, isHydrating, refQueue) {
  let i, oldVNode, childVNode, newDom, firstChildDom;
  let oldChildren = oldParentVNode && oldParentVNode._children || EMPTY_ARR;
  let newChildrenLength = renderResult.length;
  newParentVNode._nextDom = oldDom;
  constructNewChildrenArray(newParentVNode, renderResult, oldChildren);
  oldDom = newParentVNode._nextDom;
  for (i = 0; i < newChildrenLength; i++) {
    childVNode = newParentVNode._children[i];
    if (childVNode == null || typeof childVNode == "boolean" || typeof childVNode == "function") {
      continue;
    }
    if (childVNode._index === -1) {
      oldVNode = EMPTY_OBJ;
    } else {
      oldVNode = oldChildren[childVNode._index] || EMPTY_OBJ;
    }
    childVNode._index = i;
    diff(
      parentDom,
      childVNode,
      oldVNode,
      globalContext,
      namespace,
      excessDomChildren,
      commitQueue,
      oldDom,
      isHydrating,
      refQueue
    );
    newDom = childVNode._dom;
    if (childVNode.ref && oldVNode.ref != childVNode.ref) {
      if (oldVNode.ref) {
        applyRef(oldVNode.ref, null, childVNode);
      }
      refQueue.push(
        childVNode.ref,
        childVNode._component || newDom,
        childVNode
      );
    }
    if (firstChildDom == null && newDom != null) {
      firstChildDom = newDom;
    }
    if (childVNode._flags & INSERT_VNODE || oldVNode._children === childVNode._children) {
      oldDom = insert(childVNode, oldDom, parentDom);
    } else if (typeof childVNode.type == "function" && childVNode._nextDom !== void 0) {
      oldDom = childVNode._nextDom;
    } else if (newDom) {
      oldDom = newDom.nextSibling;
    }
    childVNode._nextDom = void 0;
    childVNode._flags &= ~(INSERT_VNODE | MATCHED);
  }
  newParentVNode._nextDom = oldDom;
  newParentVNode._dom = firstChildDom;
}
function constructNewChildrenArray(newParentVNode, renderResult, oldChildren) {
  let i;
  let childVNode;
  let oldVNode;
  const newChildrenLength = renderResult.length;
  let oldChildrenLength = oldChildren.length, remainingOldChildren = oldChildrenLength;
  let skew = 0;
  newParentVNode._children = [];
  for (i = 0; i < newChildrenLength; i++) {
    childVNode = renderResult[i];
    if (childVNode == null || typeof childVNode == "boolean" || typeof childVNode == "function") {
      childVNode = newParentVNode._children[i] = null;
    } else if (typeof childVNode == "string" || typeof childVNode == "number" || // eslint-disable-next-line valid-typeof
    typeof childVNode == "bigint" || childVNode.constructor == String) {
      childVNode = newParentVNode._children[i] = createVNode(
        null,
        childVNode,
        null,
        null,
        null
      );
    } else if (isArray(childVNode)) {
      childVNode = newParentVNode._children[i] = createVNode(
        Fragment,
        { children: childVNode },
        null,
        null,
        null
      );
    } else if (childVNode.constructor === void 0 && childVNode._depth > 0) {
      childVNode = newParentVNode._children[i] = createVNode(
        childVNode.type,
        childVNode.props,
        childVNode.key,
        childVNode.ref ? childVNode.ref : null,
        childVNode._original
      );
    } else {
      childVNode = newParentVNode._children[i] = childVNode;
    }
    const skewedIndex = i + skew;
    if (childVNode == null) {
      oldVNode = oldChildren[skewedIndex];
      if (oldVNode && oldVNode.key == null && oldVNode._dom && (oldVNode._flags & MATCHED) === 0) {
        if (oldVNode._dom == newParentVNode._nextDom) {
          newParentVNode._nextDom = getDomSibling(oldVNode);
        }
        unmount(oldVNode, oldVNode, false);
        oldChildren[skewedIndex] = null;
        remainingOldChildren--;
      }
      continue;
    }
    childVNode._parent = newParentVNode;
    childVNode._depth = newParentVNode._depth + 1;
    const matchingIndex = findMatchingIndex(
      childVNode,
      oldChildren,
      skewedIndex,
      remainingOldChildren
    );
    childVNode._index = matchingIndex;
    oldVNode = null;
    if (matchingIndex !== -1) {
      oldVNode = oldChildren[matchingIndex];
      remainingOldChildren--;
      if (oldVNode) {
        oldVNode._flags |= MATCHED;
      }
    }
    const isMounting = oldVNode == null || oldVNode._original === null;
    if (isMounting) {
      if (matchingIndex == -1) {
        skew--;
      }
      if (typeof childVNode.type != "function") {
        childVNode._flags |= INSERT_VNODE;
      }
    } else if (matchingIndex !== skewedIndex) {
      if (matchingIndex == skewedIndex - 1) {
        skew = matchingIndex - skewedIndex;
      } else if (matchingIndex == skewedIndex + 1) {
        skew++;
      } else if (matchingIndex > skewedIndex) {
        if (remainingOldChildren > newChildrenLength - skewedIndex) {
          skew += matchingIndex - skewedIndex;
        } else {
          skew--;
        }
      } else if (matchingIndex < skewedIndex) {
        skew++;
      }
      if (matchingIndex !== i + skew) {
        childVNode._flags |= INSERT_VNODE;
      }
    }
  }
  if (remainingOldChildren) {
    for (i = 0; i < oldChildrenLength; i++) {
      oldVNode = oldChildren[i];
      if (oldVNode != null && (oldVNode._flags & MATCHED) === 0) {
        if (oldVNode._dom == newParentVNode._nextDom) {
          newParentVNode._nextDom = getDomSibling(oldVNode);
        }
        unmount(oldVNode, oldVNode);
      }
    }
  }
}
function insert(parentVNode, oldDom, parentDom) {
  if (typeof parentVNode.type == "function") {
    let children = parentVNode._children;
    for (let i = 0; children && i < children.length; i++) {
      if (children[i]) {
        children[i]._parent = parentVNode;
        oldDom = insert(children[i], oldDom, parentDom);
      }
    }
    return oldDom;
  } else if (parentVNode._dom != oldDom) {
    if (oldDom && parentVNode.type && // @ts-expect-error olDom should be present on a DOM node
    !parentDom.contains(oldDom)) {
      oldDom = getDomSibling(parentVNode);
    }
    parentDom.insertBefore(parentVNode._dom, oldDom || null);
    oldDom = parentVNode._dom;
  }
  do {
    oldDom = oldDom && oldDom.nextSibling;
  } while (oldDom != null && oldDom.nodeType === 8);
  return oldDom;
}
function findMatchingIndex(childVNode, oldChildren, skewedIndex, remainingOldChildren) {
  const key = childVNode.key;
  const type = childVNode.type;
  let x = skewedIndex - 1;
  let y = skewedIndex + 1;
  let oldVNode = oldChildren[skewedIndex];
  let shouldSearch = remainingOldChildren > (oldVNode != null && (oldVNode._flags & MATCHED) === 0 ? 1 : 0);
  if (oldVNode === null || oldVNode && key == oldVNode.key && type === oldVNode.type && (oldVNode._flags & MATCHED) === 0) {
    return skewedIndex;
  } else if (shouldSearch) {
    while (x >= 0 || y < oldChildren.length) {
      if (x >= 0) {
        oldVNode = oldChildren[x];
        if (oldVNode && (oldVNode._flags & MATCHED) === 0 && key == oldVNode.key && type === oldVNode.type) {
          return x;
        }
        x--;
      }
      if (y < oldChildren.length) {
        oldVNode = oldChildren[y];
        if (oldVNode && (oldVNode._flags & MATCHED) === 0 && key == oldVNode.key && type === oldVNode.type) {
          return y;
        }
        y++;
      }
    }
  }
  return -1;
}

// node_modules/onejs-preact/diff/props.js
function setStyle(style, key, value) {
  if (key[0] === "-") {
    style.setProperty(key, value == null ? "" : value);
  } else if (value == null) {
    style[key] = "";
  } else if (typeof value != "number" || IS_NON_DIMENSIONAL.test(key)) {
    style[key] = value;
  } else {
    style[key] = value;
  }
}
var eventClock = 0;
var MAX_ENTRIES = 1e3;
var eventDispatchTimes = /* @__PURE__ */ new Map();
function setProperty(dom, name, value, oldValue, namespace) {
  let useCapture;
  o:
    if (name === "style") {
      if (typeof value == "string") {
        dom.style.cssText = value;
      } else {
        if (typeof oldValue == "string") {
          dom.style.cssText = oldValue = "";
        }
        if (oldValue) {
          for (name in oldValue) {
            if (!(value && name in value)) {
              setStyle(dom.style, name, "");
            }
          }
        }
        if (value) {
          for (name in value) {
            if (!oldValue || value[name] !== oldValue[name]) {
              setStyle(dom.style, name, value[name]);
            }
          }
        }
      }
    } else if (name[0] === "o" && name[1] === "n") {
      useCapture = name !== (name = name.replace(/(PointerCapture)$|Capture$/i, "$1"));
      name = name.slice(2);
      if (!dom._listeners)
        dom._listeners = {};
      dom._listeners[name + useCapture] = value;
      if (value) {
        if (!oldValue) {
          value._attached = eventClock;
          dom.addEventListener(
            name,
            useCapture ? eventProxyCapture : eventProxy,
            useCapture
          );
        } else {
          value._attached = oldValue._attached;
        }
      } else {
        dom.removeEventListener(
          name,
          useCapture ? eventProxyCapture : eventProxy,
          useCapture
        );
      }
    } else {
      if (namespace == "http://www.w3.org/2000/svg") {
        name = name.replace(/xlink(H|:h)/, "h").replace(/sName$/, "s");
      } else if (name != "width" && name != "height" && name != "href" && name != "list" && name != "form" && // Default value in browsers is `-1` and an empty string is
      // cast to `0` instead
      name != "tabIndex" && name != "download" && name != "rowSpan" && name != "colSpan" && name != "role" && name != "popover" && name in dom.ve) {
        try {
          dom.setAttribute(name, value == null ? "" : value);
          break o;
        } catch (e) {
        }
      }
      if (typeof value == "function") {
      } else if (value != null && typeof value !== "undefined") {
        dom.setAttribute(name, name == "popover" && value == true ? "" : value);
      } else {
        dom.removeAttribute(name);
      }
    }
}
function createEventProxy(useCapture) {
  return function(e) {
    if (this._listeners) {
      let eventName = e.GetType().Name.replace("Event", "");
      eventName = eventName === "Change`1" ? "ValueChanged" : eventName;
      const eventHandler = this._listeners[eventName + useCapture];
      const key = e.timestamp;
      if (!eventDispatchTimes.has(key)) {
        eventDispatchTimes.set(key, eventClock++);
        if (eventDispatchTimes.size >= MAX_ENTRIES) {
          const oldestKey = eventDispatchTimes.keys().next().value;
          eventDispatchTimes.delete(oldestKey);
        }
      } else {
        const tmpClock = eventDispatchTimes.get(key);
        eventDispatchTimes.delete(key);
        eventDispatchTimes.set(key, tmpClock);
      }
      const dispatchTime = eventDispatchTimes.get(key);
      if (dispatchTime < eventHandler._attached) {
        return;
      }
      return eventHandler(options_default.event ? options_default.event(e) : e);
    }
  };
}
var eventProxy = createEventProxy(false);
var eventProxyCapture = createEventProxy(true);

// node_modules/onejs-preact/diff/index.js
function diff(parentDom, newVNode, oldVNode, globalContext, namespace, excessDomChildren, commitQueue, oldDom, isHydrating, refQueue) {
  let tmp, newType = newVNode.type;
  if (newVNode.constructor !== void 0)
    return null;
  if (oldVNode._flags & MODE_SUSPENDED) {
    isHydrating = !!(oldVNode._flags & MODE_HYDRATE);
    oldDom = newVNode._dom = oldVNode._dom;
    excessDomChildren = [oldDom];
  }
  if (tmp = options_default._diff)
    tmp(newVNode);
  outer:
    if (typeof newType == "function") {
      try {
        let c, isNew, oldProps, oldState, snapshot, clearProcessingException;
        let newProps = newVNode.props;
        const isClassComponent = "prototype" in newType && newType.prototype.render;
        tmp = newType.contextType;
        let provider = tmp && globalContext[tmp._id];
        let componentContext = tmp ? provider ? provider.props.value : tmp._defaultValue : globalContext;
        if (oldVNode._component) {
          c = newVNode._component = oldVNode._component;
          clearProcessingException = c._processingException = c._pendingError;
        } else {
          if (isClassComponent) {
            newVNode._component = c = new newType(newProps, componentContext);
          } else {
            newVNode._component = c = new BaseComponent(
              newProps,
              componentContext
            );
            c.constructor = newType;
            c.render = doRender;
          }
          if (provider)
            provider.sub(c);
          c.props = newProps;
          if (!c.state)
            c.state = {};
          c.context = componentContext;
          c._globalContext = globalContext;
          isNew = c._dirty = true;
          c._renderCallbacks = [];
          c._stateCallbacks = [];
        }
        if (isClassComponent && c._nextState == null) {
          c._nextState = c.state;
        }
        if (isClassComponent && newType.getDerivedStateFromProps != null) {
          if (c._nextState == c.state) {
            c._nextState = assign({}, c._nextState);
          }
          assign(
            c._nextState,
            newType.getDerivedStateFromProps(newProps, c._nextState)
          );
        }
        oldProps = c.props;
        oldState = c.state;
        c._vnode = newVNode;
        if (isNew) {
          if (isClassComponent && newType.getDerivedStateFromProps == null && c.componentWillMount != null) {
            c.componentWillMount();
          }
          if (isClassComponent && c.componentDidMount != null) {
            c._renderCallbacks.push(c.componentDidMount);
          }
        } else {
          if (isClassComponent && newType.getDerivedStateFromProps == null && newProps !== oldProps && c.componentWillReceiveProps != null) {
            c.componentWillReceiveProps(newProps, componentContext);
          }
          if (!c._force && (c.shouldComponentUpdate != null && c.shouldComponentUpdate(
            newProps,
            c._nextState,
            componentContext
          ) === false || newVNode._original === oldVNode._original)) {
            if (newVNode._original !== oldVNode._original) {
              c.props = newProps;
              c.state = c._nextState;
              c._dirty = false;
            }
            newVNode._dom = oldVNode._dom;
            newVNode._children = oldVNode._children;
            newVNode._children.forEach((vnode) => {
              if (vnode)
                vnode._parent = newVNode;
            });
            for (let i = 0; i < c._stateCallbacks.length; i++) {
              c._renderCallbacks.push(c._stateCallbacks[i]);
            }
            c._stateCallbacks = [];
            if (c._renderCallbacks.length) {
              commitQueue.push(c);
            }
            break outer;
          }
          if (c.componentWillUpdate != null) {
            c.componentWillUpdate(newProps, c._nextState, componentContext);
          }
          if (isClassComponent && c.componentDidUpdate != null) {
            c._renderCallbacks.push(() => {
              c.componentDidUpdate(oldProps, oldState, snapshot);
            });
          }
        }
        c.context = componentContext;
        c.props = newProps;
        c._parentDom = parentDom;
        c._force = false;
        let renderHook = options_default._render, count = 0;
        if (isClassComponent) {
          c.state = c._nextState;
          c._dirty = false;
          if (renderHook)
            renderHook(newVNode);
          tmp = c.render(c.props, c.state, c.context);
          for (let i = 0; i < c._stateCallbacks.length; i++) {
            c._renderCallbacks.push(c._stateCallbacks[i]);
          }
          c._stateCallbacks = [];
        } else {
          do {
            c._dirty = false;
            if (renderHook)
              renderHook(newVNode);
            tmp = c.render(c.props, c.state, c.context);
            c.state = c._nextState;
          } while (c._dirty && ++count < 25);
        }
        c.state = c._nextState;
        if (c.getChildContext != null) {
          globalContext = assign(assign({}, globalContext), c.getChildContext());
        }
        if (isClassComponent && !isNew && c.getSnapshotBeforeUpdate != null) {
          snapshot = c.getSnapshotBeforeUpdate(oldProps, oldState);
        }
        let isTopLevelFragment = tmp != null && tmp.type === Fragment && tmp.key == null;
        let renderResult = isTopLevelFragment ? tmp.props.children : tmp;
        diffChildren(
          parentDom,
          isArray(renderResult) ? renderResult : [renderResult],
          newVNode,
          oldVNode,
          globalContext,
          namespace,
          excessDomChildren,
          commitQueue,
          oldDom,
          isHydrating,
          refQueue
        );
        c.base = newVNode._dom;
        newVNode._flags &= RESET_MODE;
        if (c._renderCallbacks.length) {
          commitQueue.push(c);
        }
        if (clearProcessingException) {
          c._pendingError = c._processingException = null;
        }
      } catch (e) {
        newVNode._original = null;
        if (isHydrating || excessDomChildren != null) {
          newVNode._flags |= isHydrating ? MODE_HYDRATE | MODE_SUSPENDED : MODE_HYDRATE;
          while (oldDom && oldDom.nodeType === 8 && oldDom.nextSibling) {
            oldDom = oldDom.nextSibling;
          }
          excessDomChildren[excessDomChildren.indexOf(oldDom)] = null;
          newVNode._dom = oldDom;
        } else {
          newVNode._dom = oldVNode._dom;
          newVNode._children = oldVNode._children;
        }
        options_default._catchError(e, newVNode, oldVNode);
      }
    } else if (excessDomChildren == null && newVNode._original === oldVNode._original) {
      newVNode._children = oldVNode._children;
      newVNode._dom = oldVNode._dom;
    } else {
      newVNode._dom = diffElementNodes(
        oldVNode._dom,
        newVNode,
        oldVNode,
        globalContext,
        namespace,
        excessDomChildren,
        commitQueue,
        isHydrating,
        refQueue
      );
    }
  if (tmp = options_default.diffed)
    tmp(newVNode);
}
function commitRoot(commitQueue, root, refQueue) {
  root._nextDom = void 0;
  for (let i = 0; i < refQueue.length; i++) {
    applyRef(refQueue[i], refQueue[++i], refQueue[++i]);
  }
  if (options_default._commit)
    options_default._commit(root, commitQueue);
  commitQueue.some((c) => {
    try {
      commitQueue = c._renderCallbacks;
      c._renderCallbacks = [];
      commitQueue.some((cb) => {
        cb.call(c);
      });
    } catch (e) {
      options_default._catchError(e, c._vnode);
    }
  });
}
function diffElementNodes(dom, newVNode, oldVNode, globalContext, namespace, excessDomChildren, commitQueue, isHydrating, refQueue) {
  let oldProps = oldVNode.props;
  let newProps = newVNode.props;
  let nodeType = (
    /** @type {string} */
    newVNode.type
  );
  let i;
  let newHtml;
  let oldHtml;
  let newChildren;
  let value;
  let inputValue;
  let checked;
  if (nodeType === "svg")
    namespace = "http://www.w3.org/2000/svg";
  else if (nodeType === "math")
    namespace = "http://www.w3.org/1998/Math/MathML";
  else if (!namespace)
    namespace = "http://www.w3.org/1999/xhtml";
  if (excessDomChildren != null) {
    for (i = 0; i < excessDomChildren.length; i++) {
      value = excessDomChildren[i];
      if (value && "setAttribute" in value === !!nodeType && (nodeType ? value.localName === nodeType : value.nodeType === 3)) {
        dom = value;
        excessDomChildren[i] = null;
        break;
      }
    }
  }
  if (dom == null) {
    if (nodeType === null) {
      return globalThis.onejsDocument.createTextNode(newProps);
    }
    dom = globalThis.onejsDocument.createElementNS(
      // MODDED
      namespace,
      nodeType,
      newProps.is && newProps
    );
    excessDomChildren = null;
    isHydrating = false;
  }
  if (nodeType === null) {
    if (oldProps !== newProps && (!isHydrating || dom.data !== newProps)) {
      dom.data = newProps;
    }
  } else {
    excessDomChildren = excessDomChildren && slice.call(dom.childNodes);
    oldProps = oldVNode.props || EMPTY_OBJ;
    if (!isHydrating && excessDomChildren != null) {
      oldProps = {};
      for (i = 0; i < dom.attributes.length; i++) {
        value = dom.attributes[i];
        oldProps[value.name] = value.value;
      }
    }
    for (i in oldProps) {
      value = oldProps[i];
      if (i == "children") {
      } else if (i == "dangerouslySetInnerHTML") {
        oldHtml = value;
      } else if (i !== "key" && !(i in newProps)) {
        if (i == "value" && "defaultValue" in newProps || i == "checked" && "defaultChecked" in newProps) {
          continue;
        }
        setProperty(dom, i, null, value, namespace);
      }
    }
    for (i in newProps) {
      value = newProps[i];
      if (i == "children") {
        newChildren = value;
      } else if (i == "dangerouslySetInnerHTML") {
        newHtml = value;
      } else if (i == "value") {
        inputValue = value;
      } else if (i == "checked") {
        checked = value;
      } else if (i !== "key" && (!isHydrating || typeof value == "function") && oldProps[i] !== value) {
        setProperty(dom, i, value, oldProps[i], namespace);
      }
    }
    if (newHtml) {
      if (!isHydrating && (!oldHtml || newHtml.__html !== oldHtml.__html && newHtml.__html !== dom.innerHTML)) {
        dom.innerHTML = newHtml.__html;
      }
      newVNode._children = [];
    } else {
      if (oldHtml)
        dom.innerHTML = "";
      diffChildren(
        dom,
        isArray(newChildren) ? newChildren : [newChildren],
        newVNode,
        oldVNode,
        globalContext,
        nodeType === "foreignObject" ? "http://www.w3.org/1999/xhtml" : namespace,
        excessDomChildren,
        commitQueue,
        excessDomChildren ? excessDomChildren[0] : oldVNode._children && getDomSibling(oldVNode, 0),
        isHydrating,
        refQueue
      );
      if (excessDomChildren != null) {
        for (i = excessDomChildren.length; i--; ) {
          if (excessDomChildren[i] != null)
            removeNode(excessDomChildren[i]);
        }
      }
    }
    if (!isHydrating) {
      i = "value";
      if (inputValue !== void 0 && // #2756 For the <progress>-element the initial value is 0,
      // despite the attribute not being present. When the attribute
      // is missing the progress bar is treated as indeterminate.
      // To fix that we'll always update it when it is 0 for progress elements
      (inputValue !== dom[i] || nodeType === "progress" && !inputValue || // This is only for IE 11 to fix <select> value not being updated.
      // To avoid a stale select value we need to set the option.value
      // again, which triggers IE11 to re-evaluate the select value
      nodeType === "option" && inputValue !== oldProps[i])) {
        setProperty(dom, i, inputValue, oldProps[i], namespace);
      }
      i = "checked";
      if (checked !== void 0 && checked !== dom[i]) {
        setProperty(dom, i, checked, oldProps[i], namespace);
      }
    }
  }
  return dom;
}
function applyRef(ref, value, vnode) {
  try {
    if (typeof ref == "function") {
      let hasRefUnmount = typeof ref._unmount == "function";
      if (hasRefUnmount) {
        ref._unmount();
      }
      if (!hasRefUnmount || value != null) {
        ref._unmount = ref(value);
      }
    } else
      ref.current = value;
  } catch (e) {
    options_default._catchError(e, vnode);
  }
}
function unmount(vnode, parentVNode, skipRemove) {
  let r;
  if (options_default.unmount)
    options_default.unmount(vnode);
  if (r = vnode.ref) {
    if (!r.current || r.current === vnode._dom) {
      applyRef(r, null, parentVNode);
    }
  }
  if ((r = vnode._component) != null) {
    if (r.componentWillUnmount) {
      try {
        r.componentWillUnmount();
      } catch (e) {
        options_default._catchError(e, parentVNode);
      }
    }
    r.base = r._parentDom = null;
  }
  if (r = vnode._children) {
    for (let i = 0; i < r.length; i++) {
      if (r[i]) {
        unmount(
          r[i],
          parentVNode,
          skipRemove || typeof vnode.type != "function"
        );
      }
    }
  }
  if (!skipRemove && vnode._dom != null) {
    removeNode(vnode._dom);
  }
  vnode._component = vnode._parent = vnode._dom = vnode._nextDom = void 0;
}
function doRender(props, state, context) {
  return this.constructor(props, context);
}

// node_modules/onejs-preact/hooks/index.js
var currentIndex;
var currentComponent;
var previousComponent;
var currentHook = 0;
var afterPaintEffects = [];
var options2 = (
  /** @type {import('./internal').Options} */
  options_default
);
var oldBeforeDiff = options2._diff;
var oldBeforeRender = options2._render;
var oldAfterDiff = options2.diffed;
var oldCommit = options2._commit;
var oldBeforeUnmount = options2.unmount;
var oldRoot = options2._root;
var RAF_TIMEOUT = 100;
var prevRaf;
options2._diff = (vnode) => {
  currentComponent = null;
  if (oldBeforeDiff)
    oldBeforeDiff(vnode);
};
options2._root = (vnode, parentDom) => {
  if (vnode && parentDom._children && parentDom._children._mask) {
    vnode._mask = parentDom._children._mask;
  }
  if (oldRoot)
    oldRoot(vnode, parentDom);
};
options2._render = (vnode) => {
  if (oldBeforeRender)
    oldBeforeRender(vnode);
  currentComponent = vnode._component;
  currentIndex = 0;
  const hooks = currentComponent.__hooks;
  if (hooks) {
    if (previousComponent === currentComponent) {
      hooks._pendingEffects = [];
      currentComponent._renderCallbacks = [];
      hooks._list.forEach((hookItem) => {
        if (hookItem._nextValue) {
          hookItem._value = hookItem._nextValue;
        }
        hookItem._pendingArgs = hookItem._nextValue = void 0;
      });
    } else {
      hooks._pendingEffects.forEach(invokeCleanup);
      hooks._pendingEffects.forEach(invokeEffect);
      hooks._pendingEffects = [];
      currentIndex = 0;
    }
  }
  previousComponent = currentComponent;
};
options2.diffed = (vnode) => {
  if (oldAfterDiff)
    oldAfterDiff(vnode);
  const c = vnode._component;
  if (c && c.__hooks) {
    if (c.__hooks._pendingEffects.length)
      afterPaint(afterPaintEffects.push(c));
    c.__hooks._list.forEach((hookItem) => {
      if (hookItem._pendingArgs) {
        hookItem._args = hookItem._pendingArgs;
      }
      hookItem._pendingArgs = void 0;
    });
  }
  previousComponent = currentComponent = null;
};
options2._commit = (vnode, commitQueue) => {
  commitQueue.some((component) => {
    try {
      component._renderCallbacks.forEach(invokeCleanup);
      component._renderCallbacks = component._renderCallbacks.filter(
        (cb) => cb._value ? invokeEffect(cb) : true
      );
    } catch (e) {
      commitQueue.some((c) => {
        if (c._renderCallbacks)
          c._renderCallbacks = [];
      });
      commitQueue = [];
      options2._catchError(e, component._vnode);
    }
  });
  if (oldCommit)
    oldCommit(vnode, commitQueue);
};
options2.unmount = (vnode) => {
  if (oldBeforeUnmount)
    oldBeforeUnmount(vnode);
  const c = vnode._component;
  if (c && c.__hooks) {
    let hasErrored;
    c.__hooks._list.forEach((s) => {
      try {
        invokeCleanup(s);
      } catch (e) {
        hasErrored = e;
      }
    });
    c.__hooks = void 0;
    if (hasErrored)
      options2._catchError(hasErrored, c._vnode);
  }
};
function getHookState(index, type) {
  if (options2._hook) {
    options2._hook(currentComponent, index, currentHook || type);
  }
  currentHook = 0;
  const hooks = currentComponent.__hooks || (currentComponent.__hooks = {
    _list: [],
    _pendingEffects: []
  });
  if (index >= hooks._list.length) {
    hooks._list.push({});
  }
  return hooks._list[index];
}
function useState(initialState) {
  currentHook = 1;
  return useReducer(invokeOrReturn, initialState);
}
function useReducer(reducer, initialState, init) {
  const hookState = getHookState(currentIndex++, 2);
  hookState._reducer = reducer;
  if (!hookState._component) {
    hookState._value = [
      !init ? invokeOrReturn(void 0, initialState) : init(initialState),
      (action) => {
        const currentValue = hookState._nextValue ? hookState._nextValue[0] : hookState._value[0];
        const nextValue = hookState._reducer(currentValue, action);
        if (currentValue !== nextValue) {
          hookState._nextValue = [nextValue, hookState._value[1]];
          hookState._component.setState({});
        }
      }
    ];
    hookState._component = currentComponent;
    if (!currentComponent._hasScuFromHooks) {
      let updateHookState = function(p, s, c) {
        if (!hookState._component.__hooks)
          return true;
        const isStateHook = (x) => !!x._component;
        const stateHooks = hookState._component.__hooks._list.filter(isStateHook);
        const allHooksEmpty = stateHooks.every((x) => !x._nextValue);
        if (allHooksEmpty) {
          return prevScu ? prevScu.call(this, p, s, c) : true;
        }
        let shouldUpdate = false;
        stateHooks.forEach((hookItem) => {
          if (hookItem._nextValue) {
            const currentValue = hookItem._value[0];
            hookItem._value = hookItem._nextValue;
            hookItem._nextValue = void 0;
            if (currentValue !== hookItem._value[0])
              shouldUpdate = true;
          }
        });
        return shouldUpdate || hookState._component.props !== p ? prevScu ? prevScu.call(this, p, s, c) : true : false;
      };
      currentComponent._hasScuFromHooks = true;
      let prevScu = currentComponent.shouldComponentUpdate;
      const prevCWU = currentComponent.componentWillUpdate;
      currentComponent.componentWillUpdate = function(p, s, c) {
        if (this._force) {
          let tmp = prevScu;
          prevScu = void 0;
          updateHookState(p, s, c);
          prevScu = tmp;
        }
        if (prevCWU)
          prevCWU.call(this, p, s, c);
      };
      currentComponent.shouldComponentUpdate = updateHookState;
    }
  }
  return hookState._nextValue || hookState._value;
}
function useEffect(callback, args) {
  const state = getHookState(currentIndex++, 3);
  if (!options2._skipEffects && argsChanged(state._args, args)) {
    state._value = callback;
    state._pendingArgs = args;
    currentComponent.__hooks._pendingEffects.push(state);
  }
}
function useMemo(factory, args) {
  const state = getHookState(currentIndex++, 7);
  if (argsChanged(state._args, args)) {
    state._value = factory();
    state._args = args;
    state._factory = factory;
  }
  return state._value;
}
function flushAfterPaintEffects() {
  let component;
  while (component = afterPaintEffects.shift()) {
    if (!component._parentDom || !component.__hooks)
      continue;
    try {
      component.__hooks._pendingEffects.forEach(invokeCleanup);
      component.__hooks._pendingEffects.forEach(invokeEffect);
      component.__hooks._pendingEffects = [];
    } catch (e) {
      component.__hooks._pendingEffects = [];
      options2._catchError(e, component._vnode);
    }
  }
}
var HAS_RAF = typeof requestAnimationFrame == "function";
function afterNextFrame(callback) {
  const done = () => {
    clearTimeout(timeout);
    if (HAS_RAF)
      cancelAnimationFrame(raf);
    setTimeout(callback);
  };
  const timeout = setTimeout(done, RAF_TIMEOUT);
  let raf;
  if (HAS_RAF) {
    raf = requestAnimationFrame(done);
  }
}
function afterPaint(newQueueLength) {
  if (newQueueLength === 1 || prevRaf !== options2.requestAnimationFrame) {
    prevRaf = options2.requestAnimationFrame;
    (prevRaf || afterNextFrame)(flushAfterPaintEffects);
  }
}
function invokeCleanup(hook) {
  const comp = currentComponent;
  let cleanup = hook._cleanup;
  if (typeof cleanup == "function") {
    hook._cleanup = void 0;
    cleanup();
  }
  currentComponent = comp;
}
function invokeEffect(hook) {
  const comp = currentComponent;
  hook._cleanup = hook._value();
  currentComponent = comp;
}
function argsChanged(oldArgs, newArgs) {
  return !oldArgs || oldArgs.length !== newArgs.length || newArgs.some((arg, index) => arg !== oldArgs[index]);
}
function invokeOrReturn(arg, f) {
  return typeof f == "function" ? f(arg) : f;
}

// plugins/pomodoro/index.tsx
var BG = "#0b1020";
var CARD = "#111827";
var PANEL = "#1e293b";
var TEXT = "#e5e7eb";
var DIM = "#94a3b8";
var ACCENT = "#7dd3fc";
var OK = "#34d399";
var WARN = "#f59e0b";
var SETTINGS_FILE = "window-manager/pomodoro-settings.json";
var HIDE_TARGET_PATHS = [
  "Paremt/PCPlatform/Canvas/UI/UI_FacilityPomodoro",
  "Paremt/PCPlatform/Canvas/UI/UI_FacilityPlayerLevel"
];
var OFFSET_TARGET_PATH = "Paremt/PCPlatform/Canvas/UI/MostFrontArea/TopIcons";
var OFFSET_Y_WHEN_HIDDEN = 250;
var DEFAULT_SETTINGS = {
  hideDefaultPomodoroUI: true,
  showSeconds: false
};
var offsetTargetOrigin = null;
var pad2 = (n) => String(n).padStart(2, "0");
var hhmmss = (s) => `${pad2(Math.floor(Math.max(0, s) / 3600))}:${pad2(Math.floor(Math.max(0, s) % 3600 / 60))}:${pad2(Math.floor(Math.max(0, s) % 60))}`;
var json = (v, fb) => {
  try {
    return typeof v === "string" ? JSON.parse(v) : v;
  } catch {
    return fb;
  }
};
var clamp = (v, min, max) => Math.max(min, Math.min(max, v));
var loadPomodoroSettings = () => {
  try {
    if (!chill?.io?.exists?.(SETTINGS_FILE))
      return DEFAULT_SETTINGS;
    const txt = chill?.io?.readText?.(SETTINGS_FILE);
    const parsed = json(txt, null);
    if (!parsed || typeof parsed !== "object")
      return DEFAULT_SETTINGS;
    return {
      hideDefaultPomodoroUI: !!parsed.hideDefaultPomodoroUI,
      showSeconds: !!parsed.showSeconds
    };
  } catch {
    return DEFAULT_SETTINGS;
  }
};
var savePomodoroSettings = (settings) => {
  try {
    chill?.io?.writeText?.(SETTINGS_FILE, JSON.stringify(settings, null, 2));
  } catch {
  }
};
var setNodeActive = (path, active) => {
  if (!path || !path.trim())
    return;
  chill?.ui?.setActive?.(path, active);
};
var applyOffsetForTarget = (hideEnabled) => {
  if (!OFFSET_TARGET_PATH || !OFFSET_TARGET_PATH.trim())
    return;
  if (!hideEnabled) {
    if (offsetTargetOrigin) {
      chill?.ui?.setPosition?.(OFFSET_TARGET_PATH, offsetTargetOrigin.x, offsetTargetOrigin.y);
    }
    return;
  }
  if (!offsetTargetOrigin) {
    const rect = json(chill?.ui?.getRect?.(OFFSET_TARGET_PATH), null);
    if (!rect)
      return;
    const x = Number(rect.x);
    const y = Number(rect.y);
    if (Number.isNaN(x) || Number.isNaN(y))
      return;
    offsetTargetOrigin = { x, y };
  }
  chill?.ui?.setPosition?.(OFFSET_TARGET_PATH, offsetTargetOrigin.x, offsetTargetOrigin.y + OFFSET_Y_WHEN_HIDDEN);
};
var syncDefaultPomodoroUI = (hideEnabled) => {
  const active = !hideEnabled;
  for (const path of HIDE_TARGET_PATHS) {
    setNodeActive(path, active);
  }
  applyOffsetForTarget(hideEnabled);
};
var buildFallbackClock = () => {
  const d = /* @__PURE__ */ new Date();
  const date = `${d.getFullYear()}/${pad2(d.getMonth() + 1)}/${pad2(d.getDate())}(${d.toLocaleDateString(void 0, { weekday: "short" })})`;
  const time = `${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
  return { available: false, date, time, amPm: "", dateTime: `${date} ${time}` };
};
var readClock = (prev) => {
  const fallback = prev || buildFallbackClock();
  return json(chill?.game?.getGameClock?.(), fallback);
};
var phaseDefaultsFromState = (state) => {
  const isResting = !!state?.isResting;
  const mins = isResting ? Number(state?.breakMinutes || 5) : Number(state?.workMinutes || 25);
  const total = Math.max(1, Math.round(mins * 60));
  return { total, remain: total };
};
var nextControlState = (state) => {
  if (state?.isPaused)
    return "paused";
  if (state?.isRunning)
    return "running";
  const started = state?.type === "Work" || state?.type === "Break" || state?.isWorking || state?.isResting;
  if (!started)
    return "idle";
  return "idle";
};
var isProgressPayload = (payload) => payload && payload.remainingSeconds !== void 0 && payload.totalSeconds !== void 0;
var hasPomodoroState = (payload) => payload && payload.workMinutes !== void 0 && payload.breakMinutes !== void 0;
var hasPlayerProgress = (payload) => payload && payload.level !== void 0 && payload.nextLevelExp !== void 0;
var formatClockWithSeconds = (clock) => {
  const unixMs = Number(clock?.unixMs || 0);
  const d = unixMs > 0 ? new Date(unixMs) : /* @__PURE__ */ new Date();
  if (clock?.amPm) {
    const hh = d.getHours() % 12 || 12;
    return `${pad2(hh)}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())} ${clock.amPm}`;
  }
  return `${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`;
};
var formatClockDisplay = (clock, showSeconds) => {
  if (showSeconds)
    return formatClockWithSeconds(clock);
  const unixMs = Number(clock?.unixMs || 0);
  if (unixMs > 0) {
    const d = new Date(unixMs);
    if (clock?.amPm) {
      const hh = d.getHours() % 12 || 12;
      return `${pad2(hh)}:${pad2(d.getMinutes())}${clock?.amPm ? ` ${clock.amPm}` : ""}`;
    }
    return `${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
  }
  const fallback = `${clock?.time || "--:--"}`;
  return `${fallback}${clock?.amPm ? ` ${clock.amPm}` : ""}`;
};
var SettingsCheckbox = (props) => /* @__PURE__ */ createElement(
  "div",
  {
    style: {
      display: "Flex",
      flexDirection: "Row",
      alignItems: "Center",
      backgroundColor: CARD,
      borderRadius: 8,
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      marginBottom: 8
    },
    onPointerDown: props.onToggle
  },
  /* @__PURE__ */ createElement("div", { style: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: props.checked ? ACCENT : DIM,
    borderRadius: 4,
    marginRight: 10,
    justifyContent: "Center",
    alignItems: "Center",
    display: "Flex",
    backgroundColor: props.checked ? "rgba(125,211,252,0.16)" : "transparent",
    flexShrink: 0
  } }, props.checked && /* @__PURE__ */ createElement("div", { style: { fontSize: 12, color: TEXT } }, "\u2713")),
  /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Column", flexGrow: 1 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 12, color: TEXT } }, props.label), /* @__PURE__ */ createElement("div", { style: { fontSize: 10, color: DIM, display: props.hint ? "Flex" : "None", marginTop: 2 } }, props.hint || ""))
);
var ParamCard = (props) => {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState("");
  const submit = () => {
    const parsed = Number(draft);
    if (Number.isNaN(parsed)) {
      setEditing(false);
      return;
    }
    props.onCommit(Math.round(parsed));
    setEditing(false);
  };
  const startEdit = () => {
    setDraft(`${props.value}`);
    setEditing(true);
  };
  const chip = (t, on, bg = "rgba(125,211,252,0.15)", color = ACCENT) => /* @__PURE__ */ createElement("div", { onPointerDown: on, style: { fontSize: 12, color, backgroundColor: bg, borderRadius: 8, paddingLeft: 10, paddingRight: 10, paddingTop: 6, paddingBottom: 6 } }, t);
  return /* @__PURE__ */ createElement("div", { style: { backgroundColor: PANEL, borderRadius: 10, padding: 8, width: 98 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 10, color: DIM } }, props.title), editing ? /* @__PURE__ */ createElement(
    "textfield",
    {
      value: draft,
      onValueChanged: (e) => setDraft(e?.newValue ?? e?.target?.value ?? draft),
      onKeyDown: (e) => {
        if (e?.keyCode === 13)
          submit();
      },
      style: { fontSize: 18, color: TEXT, backgroundColor: BG, borderRadius: 6, paddingLeft: 6, paddingRight: 6, paddingTop: 2, paddingBottom: 2, marginBottom: 6 }
    }
  ) : /* @__PURE__ */ createElement("div", { style: { fontSize: 18, color: TEXT, marginBottom: 6 }, onPointerDown: startEdit }, `${props.value}${props.unit || ""}`), /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Row", justifyContent: "SpaceBetween" } }, editing ? chip("OK", submit, "rgba(52,211,153,0.16)", OK) : /* @__PURE__ */ createElement("div", { style: { display: "flex", flexDirection: "row" } }, chip("-", props.onMinus), /* @__PURE__ */ createElement("div", { style: { width: 8 } }), chip("+", props.onPlus))));
};
var PomodoroPanel = () => {
  const [clock, setClock] = useState(buildFallbackClock());
  const [pm, setPm] = useState({ available: false, type: "Unknown", loopCurrent: 0, loopTotal: 0, workMinutes: 25, breakMinutes: 5, isRunning: false, isWorking: false, isResting: false });
  const [pg, setPg] = useState({ available: false, level: 0, exp: 0, nextLevelExp: 1, totalWorkSeconds: 0 });
  const [remain, setRemain] = useState(0);
  const [total, setTotal] = useState(1);
  const [settings, setSettings] = useState(DEFAULT_SETTINGS);
  const [showSettingsPage, setShowSettingsPage] = useState(false);
  const commitWork = (v) => chill?.game?.setWorkMinutes?.(Math.max(1, v));
  const commitBreak = (v) => chill?.game?.setBreakMinutes?.(Math.max(1, v));
  const commitLoop = (v) => chill?.game?.setLoopCount?.(Math.max(1, v));
  const applyIdlePresetReset = () => {
    commitWork(45);
    commitBreak(15);
    commitLoop(3);
  };
  const syncPhaseFromState = (state, keepRemainWhenRunning = true) => {
    const defaults = phaseDefaultsFromState(state);
    setTotal(defaults.total);
    setRemain((prev) => {
      if (keepRemainWhenRunning && state?.isRunning && prev > 0)
        return prev;
      if (state?.isRunning && prev > defaults.total)
        return defaults.total;
      return defaults.remain;
    });
  };
  useEffect(() => {
    chill?.game?.ensureEventBridge?.();
    const loaded = loadPomodoroSettings();
    setSettings(loaded);
    syncDefaultPomodoroUI(loaded.hideDefaultPomodoroUI);
    const bootPm = json(chill?.game?.getPomodoroState?.(), pm);
    const bootPg = json(chill?.game?.getPlayerProgress?.(), pg);
    const bootClock = readClock(clock);
    setPm(bootPm);
    syncPhaseFromState(bootPm, false);
    setPg(bootPg);
    setClock(bootClock);
    const tk = chill?.game?.on?.("*", (evtJson) => {
      const evt = json(evtJson, null);
      if (!evt)
        return;
      const payload = evt.payload || {};
      if (evt.name === "gameClockTick" || evt.name === "gameDateChanged") {
        setClock(payload);
        return;
      }
      if (evt.name === "pomodoroProgress") {
        setRemain(Math.max(0, Math.round(Number(payload.remainingSeconds || 0))));
        setTotal(Math.max(1, Math.round(Number(payload.totalSeconds || 1))));
        if (hasPomodoroState(payload.state)) {
          setPm(payload.state);
        }
        return;
      }
      if (hasPomodoroState(payload)) {
        setPm(payload);
        syncPhaseFromState(payload, false);
      } else if (hasPomodoroState(payload.state)) {
        setPm(payload.state);
        syncPhaseFromState(payload.state, false);
      }
      if (hasPlayerProgress(payload)) {
        setPg(payload);
      } else if (String(evt.name || "").indexOf("level") >= 0 || String(evt.name || "").indexOf("exp") >= 0 || String(evt.name || "").indexOf("workSeconds") >= 0) {
        setPg(json(chill?.game?.getPlayerProgress?.(), pg));
      }
    });
    return () => {
      if (tk)
        chill?.game?.off?.(tk);
    };
  }, []);
  const updateSettings = (patch) => {
    setSettings((prev) => {
      const next = { ...prev, ...patch };
      savePomodoroSettings(next);
      syncDefaultPomodoroUI(next.hideDefaultPomodoroUI);
      return next;
    });
  };
  const timerText = useMemo(() => {
    if (remain > 0)
      return `${hhmmss(remain)}`;
    const defaults = phaseDefaultsFromState(pm);
    return `${hhmmss(defaults.remain)}`;
  }, [pm, remain]);
  const progress = useMemo(() => clamp(1 - remain / Math.max(1, total), 0, 1), [remain, total]);
  const levelProg = useMemo(() => Math.min(1, Number(pg?.exp || 0) / Math.max(1, Number(pg?.nextLevelExp || 1))), [pg]);
  const controlState = nextControlState(pm);
  const headerClockText = formatClockDisplay(clock, settings.showSeconds);
  const btn = (t, on, bg = "rgba(125,211,252,0.15)", color = ACCENT) => /* @__PURE__ */ createElement("div", { onPointerDown: on, style: { fontSize: 12, color, backgroundColor: bg, borderRadius: 8, paddingLeft: 10, paddingRight: 10, paddingTop: 6, paddingBottom: 6 } }, t);
  return /* @__PURE__ */ createElement("div", { style: { flexGrow: 1, display: "Flex", flexDirection: "Column", backgroundColor: BG, padding: 12 } }, /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Row", justifyContent: "SpaceBetween", marginBottom: 8 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 12, color: ACCENT, unityFontStyleAndWeight: "Bold", letterSpacing: 1 } }, `${clock?.date || ""}`), /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Row", alignItems: "Center" } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 12, color: TEXT } }, `${headerClockText}`), /* @__PURE__ */ createElement(
    "div",
    {
      onPointerDown: () => setShowSettingsPage((v) => !v),
      style: {
        fontSize: 12,
        color: ACCENT,
        backgroundColor: "rgba(125,211,252,0.15)",
        borderRadius: 6,
        paddingLeft: 8,
        paddingRight: 8,
        paddingTop: 4,
        paddingBottom: 4,
        marginLeft: 6
      }
    },
    showSettingsPage ? "\u2190" : "\uEB51",
    /* @__PURE__ */ createElement("div", { style: { width: 12 } })
  ))), /* @__PURE__ */ createElement("div", { style: { display: showSettingsPage ? "None" : "Flex", flexDirection: "Column", backgroundColor: CARD, borderRadius: 12, padding: 12, marginBottom: 10 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 11, color: DIM, marginBottom: 4 } }, `${pm?.isWorking ? "WORK" : pm?.isResting ? "BREAK" : "IDLE"} \xB7 LOOP ${pm?.loopCurrent || 0}/${pm?.loopTotal || 0}`), /* @__PURE__ */ createElement("div", { style: { fontSize: 42, color: TEXT, unityFontStyleAndWeight: "Bold", unityTextAlign: "MiddleCenter", marginBottom: 8 } }, timerText), /* @__PURE__ */ createElement("div", { style: { height: 3, borderRadius: 0, backgroundColor: "rgba(148,163,184,0.25)", overflow: "Hidden", marginBottom: 10 } }, /* @__PURE__ */ createElement("div", { style: { width: `${Math.round(progress * 100)}%`, height: 3, backgroundColor: pm?.isWorking ? ACCENT : WARN } })), /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Row", justifyContent: "SpaceBetween" } }, controlState === "idle" && btn("Reset", applyIdlePresetReset, "rgba(125,211,252,0.15)", ACCENT), controlState === "idle" && btn("Start", () => chill?.game?.startPomodoro?.(), "rgba(52,211,153,0.16)", OK), controlState === "running" && btn("Pause ", () => chill?.game?.togglePomodoroPause?.()), controlState === "running" && btn(" Skip ", () => chill?.game?.skipPomodoroPhase?.()), controlState === "running" && btn(" Stop ", () => chill?.game?.resetPomodoro?.(), "rgba(245,158,11,0.16)", WARN), controlState === "paused" && btn("Resume", () => chill?.game?.togglePomodoroPause?.(), "rgba(52,211,153,0.16)", OK), controlState === "paused" && btn(" Skip ", () => chill?.game?.skipPomodoroPhase?.()), controlState === "paused" && btn(" Stop ", () => chill?.game?.resetPomodoro?.(), "rgba(245,158,11,0.16)", WARN))), /* @__PURE__ */ createElement("div", { style: { display: showSettingsPage ? "None" : "Flex", flexDirection: "Row", justifyContent: "SpaceBetween", marginBottom: 10 } }, /* @__PURE__ */ createElement(
    ParamCard,
    {
      title: "Work",
      unit: "m",
      value: Number(pm?.workMinutes || 25),
      onCommit: commitWork,
      onMinus: () => commitWork(Number(pm?.workMinutes || 25) - 1),
      onPlus: () => commitWork(Number(pm?.workMinutes || 25) + 1)
    }
  ), /* @__PURE__ */ createElement(
    ParamCard,
    {
      title: "Break",
      unit: "m",
      value: Number(pm?.breakMinutes || 5),
      onCommit: commitBreak,
      onMinus: () => commitBreak(Number(pm?.breakMinutes || 5) - 1),
      onPlus: () => commitBreak(Number(pm?.breakMinutes || 5) + 1)
    }
  ), /* @__PURE__ */ createElement(
    ParamCard,
    {
      title: "Loop",
      value: Number(pm?.loopTotal || 1),
      onCommit: commitLoop,
      onMinus: () => commitLoop(Number(pm?.loopTotal || 1) - 1),
      onPlus: () => commitLoop(Number(pm?.loopTotal || 1) + 1)
    }
  )), /* @__PURE__ */ createElement("div", { style: { display: showSettingsPage ? "None" : "Flex", flexDirection: "Column", backgroundColor: CARD, borderRadius: 12, padding: 12 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 11, color: DIM, marginBottom: 4 } }, "Player Level"), /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Row", justifyContent: "SpaceBetween", marginBottom: 6 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 16, color: TEXT, unityFontStyleAndWeight: "Bold" } }, `Lv.${pg?.level || 0}`), /* @__PURE__ */ createElement("div", { style: { fontSize: 12, color: DIM } }, `${Math.round(Number(pg?.exp || 0))}/${Math.round(Number(pg?.nextLevelExp || 0))}`)), /* @__PURE__ */ createElement("div", { style: { height: 3, borderRadius: 0, backgroundColor: "rgba(148,163,184,0.25)", overflow: "Hidden", marginBottom: 6 } }, /* @__PURE__ */ createElement("div", { style: { width: `${Math.round(levelProg * 100)}%`, height: 3, backgroundColor: OK } })), /* @__PURE__ */ createElement("div", { style: { fontSize: 11, color: DIM } }, `Total Focus: ${Math.round(Number(pg?.totalWorkSeconds || 0) / 3600 * 10) / 10}h`)), /* @__PURE__ */ createElement("div", { style: { display: showSettingsPage ? "Flex" : "None", flexDirection: "Column", flexGrow: 1 } }, /* @__PURE__ */ createElement("div", { style: { backgroundColor: PANEL, borderRadius: 12, padding: 12, marginBottom: 8 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 13, color: TEXT, unityFontStyleAndWeight: "Bold", marginBottom: 8 } }, "\u8BBE\u7F6E"), /* @__PURE__ */ createElement(
    SettingsCheckbox,
    {
      checked: settings.hideDefaultPomodoroUI,
      label: "\u9690\u85CF\u6E38\u620F\u9ED8\u8BA4\u756A\u8304\u949F UI",
      hint: "\u542F\u7528\u540E\u5C06\u6309\u4E0A\u65B9\u6570\u7EC4\u9010\u9879\u9690\u85CF\uFF0C\u5E76\u5E94\u7528\u6307\u5B9A\u504F\u79FB",
      onToggle: () => updateSettings({ hideDefaultPomodoroUI: !settings.hideDefaultPomodoroUI })
    }
  ), /* @__PURE__ */ createElement(
    SettingsCheckbox,
    {
      checked: settings.showSeconds,
      label: "\u65F6\u949F\u663E\u793A\u79D2",
      hint: "\u6298\u53E0\u4E0E\u5C55\u5F00\u72B6\u6001\u7684\u53F3\u4E0A\u89D2\u65F6\u949F\u7EDF\u4E00\u8DDF\u968F\u8BE5\u9009\u9879",
      onToggle: () => updateSettings({ showSeconds: !settings.showSeconds })
    }
  )), /* @__PURE__ */ createElement("div", { style: { fontSize: 10, color: DIM, paddingLeft: 2, paddingRight: 2 } }, `\u914D\u7F6E\u4FDD\u5B58\u5728 ${SETTINGS_FILE}`)));
};
var PomodoroCompact = () => {
  const [clock, setClock] = useState(buildFallbackClock());
  const [state, setState] = useState({ isRunning: false, isResting: false, workMinutes: 25, breakMinutes: 5 });
  const [remain, setRemain] = useState(0);
  const [total, setTotal] = useState(1);
  const [settings, setSettings] = useState(DEFAULT_SETTINGS);
  const commitWork = (v) => chill?.game?.setWorkMinutes?.(Math.max(1, v));
  const commitBreak = (v) => chill?.game?.setBreakMinutes?.(Math.max(1, v));
  const commitLoop = (v) => chill?.game?.setLoopCount?.(Math.max(1, v));
  const applyIdlePresetReset = () => {
    commitWork(45);
    commitBreak(15);
    commitLoop(3);
  };
  const syncCompactState = (next, keepRemain = true) => {
    setState(next);
    const defaults = phaseDefaultsFromState(next);
    setTotal(defaults.total);
    setRemain((prev) => {
      if (keepRemain && next?.isRunning && prev > 0)
        return Math.min(prev, defaults.total);
      return defaults.remain;
    });
  };
  useEffect(() => {
    chill?.game?.ensureEventBridge?.();
    const loaded = loadPomodoroSettings();
    setSettings(loaded);
    syncDefaultPomodoroUI(loaded.hideDefaultPomodoroUI);
    const bootState = json(chill?.game?.getPomodoroState?.(), state);
    syncCompactState(bootState, false);
    const currentClock = json(chill?.game?.getGameClock?.(), clock);
    setClock(currentClock);
    const tk = chill?.game?.on?.("*", (e) => {
      const evt = json(e, null);
      if (!evt)
        return;
      const payload = evt.payload || {};
      if (evt.name === "gameClockTick" || evt.name === "gameDateChanged") {
        setClock(payload);
        return;
      }
      if (evt.name === "pomodoroProgress" && isProgressPayload(payload)) {
        setRemain(Math.max(0, Math.round(Number(payload.remainingSeconds || 0))));
        setTotal(Math.max(1, Math.round(Number(payload.totalSeconds || 1))));
        if (hasPomodoroState(payload.state)) {
          syncCompactState(payload.state);
        }
        return;
      }
      if (hasPomodoroState(payload)) {
        syncCompactState(payload, false);
      } else if (hasPomodoroState(payload.state)) {
        syncCompactState(payload.state, false);
      }
    });
    return () => {
      if (tk)
        chill?.game?.off?.(tk);
    };
  }, []);
  const controlState = nextControlState(state);
  const isBreakPhase = state?.isResting || state?.type === "Break";
  const isWorkPhase = state?.isWorking || state?.type === "Work";
  const statusText = controlState === "idle" ? "\u5F85\u5F00\u59CB" : isBreakPhase ? controlState === "paused" ? "\u4F11\u606F\u6682\u505C" : "\u4F11\u606F\u4E2D" : isWorkPhase ? controlState === "paused" ? "\u4E13\u6CE8\u6682\u505C" : "\u4E13\u6CE8\u4E2D" : controlState === "paused" ? "\u5DF2\u6682\u505C" : "\u4E13\u6CE8\u4E2D";
  const statusColor = controlState === "idle" ? DIM : isBreakPhase ? "#4CAF50" : ACCENT;
  const timerText = remain > 0 ? hhmmss(remain) : hhmmss(total);
  const compactClockText = formatClockDisplay(clock, settings.showSeconds);
  const cbtn = (t, on, bg = "rgba(125,211,252,0.15)", color = ACCENT) => /* @__PURE__ */ createElement(
    "div",
    {
      onPointerDown: on,
      style: {
        fontSize: 11,
        color,
        backgroundColor: bg,
        borderRadius: 6,
        paddingLeft: 6,
        paddingRight: 6,
        paddingTop: 4,
        paddingBottom: 4,
        unityTextAlign: "MiddleCenter",
        flexGrow: 1,
        flexBasis: 0,
        marginLeft: 3,
        marginRight: 3
      }
    },
    t
  );
  return /* @__PURE__ */ createElement("div", { style: {
    flexGrow: 1,
    display: "Flex",
    flexDirection: "Column",
    backgroundColor: CARD,
    borderRadius: 8,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8
  } }, /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Row", justifyContent: "SpaceBetween", marginBottom: 4 } }, /* @__PURE__ */ createElement("div", { style: { fontSize: 10, color: TEXT, opacity: 0.7 } }, "Pomodoro"), /* @__PURE__ */ createElement("div", { style: { fontSize: 10, color: TEXT, opacity: 0.85 } }, `${compactClockText}`)), /* @__PURE__ */ createElement("div", { style: { flexGrow: 1 } }), /* @__PURE__ */ createElement("div", { style: { fontSize: 13, color: statusColor, unityFontStyleAndWeight: "Bold", unityTextAlign: "MiddleCenter", marginBottom: 2 } }, `${statusText}`), /* @__PURE__ */ createElement("div", { style: { fontSize: 24, color: TEXT, unityFontStyleAndWeight: "Bold", unityTextAlign: "MiddleCenter", marginBottom: 8 } }, `${timerText}`), /* @__PURE__ */ createElement("div", { style: { flexGrow: 1 } }), /* @__PURE__ */ createElement("div", { style: { display: "Flex", flexDirection: "Row", justifyContent: "SpaceEvenly" } }, controlState === "idle" && cbtn("Reset", applyIdlePresetReset, "rgba(125,211,252,0.15)", ACCENT), controlState === "idle" && cbtn("Start", () => chill?.game?.startPomodoro?.(), "rgba(52,211,153,0.16)", OK), controlState === "running" && cbtn("Pause", () => chill?.game?.togglePomodoroPause?.()), controlState === "running" && cbtn("Skip", () => chill?.game?.skipPomodoroPhase?.()), controlState === "running" && cbtn("Stop", () => chill?.game?.resetPomodoro?.(), "rgba(245,158,11,0.16)", WARN), controlState === "paused" && cbtn("Resume", () => chill?.game?.togglePomodoroPause?.(), "rgba(52,211,153,0.16)", OK), controlState === "paused" && cbtn("Skip", () => chill?.game?.skipPomodoroPhase?.()), controlState === "paused" && cbtn("Stop", () => chill?.game?.resetPomodoro?.(), "rgba(245,158,11,0.16)", WARN)));
};
__registerPlugin({
  id: "pomodoro",
  title: "Pomodoro",
  width: 340,
  height: 520,
  initialX: 260,
  initialY: 120,
  resizable: true,
  launcher: { text: "\u{F0109}", background: "#0ea5e9" },
  compact: { width: 180, height: 180, component: PomodoroCompact },
  component: PomodoroPanel
});
//# sourceMappingURL=app.js.map
